pricelist = '//div [@class="iva-item-root-_lk9K photo-slider-slider-S15A_ iva-item-list-rfgcH iva-item-redesign-rop6P iva-item-responsive-_lbhG items-item-My3ih items-listItem-Gd1jN js-catalog-item-enum"]//span [@class="price-text-_YGDY text-text-LurtD text-size-s-BxGpL"]'
adress = '//div [@class="iva-item-root-_lk9K photo-slider-slider-S15A_ iva-item-list-rfgcH iva-item-redesign-rop6P iva-item-responsive-_lbhG items-item-My3ih items-listItem-Gd1jN js-catalog-item-enum"]//span [@class="geo-address-fhHd0 text-text-LurtD text-size-s-BxGpL"]/span'
href = '//div [@class="iva-item-root-_lk9K photo-slider-slider-S15A_ iva-item-list-rfgcH iva-item-redesign-rop6P iva-item-responsive-_lbhG items-item-My3ih items-listItem-Gd1jN js-catalog-item-enum"]//a [@class="link-link-MbQDP link-design-default-_nSbv title-root-zZCwT iva-item-title-py3i_ title-listRedesign-_rejR title-root_maxHeight-X6PsH"]'
pricelist_xl = '//div [@class="iva-item-root-_lk9K photo-slider-slider-S15A_ iva-item-list-rfgcH iva-item-redesign-rop6P iva-item-responsive-_lbhG iva-item-xl-_jicv items-item-My3ih items-listItem-Gd1jN js-catalog-item-enum"]//span [@class="price-text-_YGDY text-text-LurtD text-size-s-BxGpL"]'
adress_xl = '//div [@class="iva-item-root-_lk9K photo-slider-slider-S15A_ iva-item-list-rfgcH iva-item-redesign-rop6P iva-item-responsive-_lbhG iva-item-xl-_jicv items-item-My3ih items-listItem-Gd1jN js-catalog-item-enum"]//span [@class="geo-address-fhHd0 text-text-LurtD text-size-s-BxGpL"]/span'
href_xl = '//div [@class="iva-item-root-_lk9K photo-slider-slider-S15A_ iva-item-list-rfgcH iva-item-redesign-rop6P iva-item-responsive-_lbhG iva-item-xl-_jicv items-item-My3ih items-listItem-Gd1jN js-catalog-item-enum"]//a [@class="link-link-MbQDP link-design-default-_nSbv title-root-zZCwT iva-item-title-py3i_ title-listRedesign-_rejR title-root_maxHeight-X6PsH"]'
name= '//h3 [@class="title-root-zZCwT iva-item-title-py3i_ title-listRedesign-_rejR title-root_maxHeight-X6PsH text-text-LurtD text-size-s-BxGpL text-bold-SinUO"]'
URL = "https://www.avito.ru/novorossiysk/kvartiry/sdam/na_dlitelnyy_srok/2-komnatnye-ASgBAgICA0SSA8gQ8AeQUswIkFk"
NEXTBUTTON = '//span [@class="pagination-item-JJq_j pagination-item_arrow-Sttbt"][@data-marker="pagination-button/next"]'
